#
#
# cgit-docker compose example
services:
  cgit:
    # You can also use the pre-built containers hosted at ghcr and docker.
    # image: ghcr.io/bigratdad/cgit:latest
    # image: ratdad/cgit:latest
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - ENABLE_GIT_HTTP=0
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      # - ./favicon.ico:/srv/www/htdocs/cgit/favicon.ico # custom favicon
      # - ./cgit.css:/srv/www/htdocs/cgit/cgit.css # custom cgit.css
      - ./etc/cgitrc:/etc/cgitrc # You can (and should) bindmount your own cgitrc.
      - ./srv/git/:/srv/git:ro # I do not recommend creating repos from inside the container. Make it read-only.